// <auto-generated />
using System;
using BookingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookingService.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserNic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookingId");

                    b.HasIndex("TrainId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookingService.Entities.BookingRequest", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "RequestId");

                    b.HasIndex("RequestId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("BookingService.Entities.BookingSeat", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("BookingId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("BookingService.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RequestId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            AdditionalPrice = 10m,
                            Description = "Window Seat"
                        },
                        new
                        {
                            RequestId = 2,
                            AdditionalPrice = 0m,
                            Description = "Wheelchair Assistance"
                        },
                        new
                        {
                            RequestId = 3,
                            AdditionalPrice = 25m,
                            Description = "Meal"
                        });
                });

            modelBuilder.Entity("BookingService.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("TrainId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            SeatNumber = "S1",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 2,
                            SeatNumber = "S2",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 3,
                            SeatNumber = "S3",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 4,
                            SeatNumber = "S4",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 5,
                            SeatNumber = "S5",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 6,
                            SeatNumber = "S6",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 7,
                            SeatNumber = "S7",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 8,
                            SeatNumber = "S8",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 9,
                            SeatNumber = "S9",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 10,
                            SeatNumber = "S10",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 11,
                            SeatNumber = "S11",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 12,
                            SeatNumber = "S12",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 13,
                            SeatNumber = "S13",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 14,
                            SeatNumber = "S14",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 15,
                            SeatNumber = "S15",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 16,
                            SeatNumber = "S16",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 17,
                            SeatNumber = "S17",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 18,
                            SeatNumber = "S18",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 19,
                            SeatNumber = "S19",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 20,
                            SeatNumber = "S20",
                            TrainId = 1
                        },
                        new
                        {
                            SeatId = 21,
                            SeatNumber = "S1",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 22,
                            SeatNumber = "S2",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 23,
                            SeatNumber = "S3",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 24,
                            SeatNumber = "S4",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 25,
                            SeatNumber = "S5",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 26,
                            SeatNumber = "S6",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 27,
                            SeatNumber = "S7",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 28,
                            SeatNumber = "S8",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 29,
                            SeatNumber = "S9",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 30,
                            SeatNumber = "S10",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 31,
                            SeatNumber = "S11",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 32,
                            SeatNumber = "S12",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 33,
                            SeatNumber = "S13",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 34,
                            SeatNumber = "S14",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 35,
                            SeatNumber = "S15",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 36,
                            SeatNumber = "S16",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 37,
                            SeatNumber = "S17",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 38,
                            SeatNumber = "S18",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 39,
                            SeatNumber = "S19",
                            TrainId = 2
                        },
                        new
                        {
                            SeatId = 40,
                            SeatNumber = "S20",
                            TrainId = 2
                        });
                });

            modelBuilder.Entity("BookingService.Entities.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrainId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("BaseTicketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StartStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalSeatCount")
                        .HasColumnType("int");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TrainId");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainId = 1,
                            ArrivalTime = new DateTime(2026, 1, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            BaseTicketPrice = 120m,
                            DepartureTime = new DateTime(2026, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            EndStation = "Kandy",
                            StartStation = "Colombo",
                            TotalSeatCount = 20,
                            TrainNumber = "IC101"
                        },
                        new
                        {
                            TrainId = 2,
                            ArrivalTime = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            BaseTicketPrice = 90m,
                            DepartureTime = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndStation = "Galle",
                            StartStation = "Colombo",
                            TotalSeatCount = 20,
                            TrainNumber = "IC205"
                        });
                });

            modelBuilder.Entity("BookingService.Entities.Booking", b =>
                {
                    b.HasOne("BookingService.Entities.Train", "Train")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("BookingService.Entities.BookingRequest", b =>
                {
                    b.HasOne("BookingService.Entities.Booking", "Booking")
                        .WithMany("BookingRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Entities.Request", "Request")
                        .WithMany("BookingRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BookingService.Entities.BookingSeat", b =>
                {
                    b.HasOne("BookingService.Entities.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingService.Entities.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BookingService.Entities.Seat", b =>
                {
                    b.HasOne("BookingService.Entities.Train", "Train")
                        .WithMany("Seats")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("BookingService.Entities.Booking", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("BookingService.Entities.Request", b =>
                {
                    b.Navigation("BookingRequests");
                });

            modelBuilder.Entity("BookingService.Entities.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("BookingService.Entities.Train", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
